- name: Add IKE crypto config to the firewall
  panos_ike_crypto_profile:
    provider: '{{ provider }}'
    state: '{{ state }}'
    name: 'ike-{{ vpn_connection_id }}'
    dh_group: "{{ ike_dh_group }}"
    authentication: "{{ ike_authentication }}"
    encryption: "{{ ike_encryption }}"
    lifetime_seconds: "{{ ike_lifetime }}"
    commit: False
    
    
- name: Add IKE gateway config to the firewall
  panos_ike_gateway:
    provider: '{{ provider }}'
    state: '{{ state }}'
    name: 'ikegw-{{ vpn_connection_id }}'
    interface: "{{ ike_interface }}"
    enable_liveness_check: True
    enable_passive_mode: 'no'
    liveness_check_interval: '10'
    peer_ip_value: '{{ aws_peer_ip_value }}'
    pre_shared_key: '{{ ike_preshared_key }}'
    ikev2_crypto_profile: 'ike-{{ vpn_connection_id }}'
    commit: False
    
    
- name: Add IPSec crypto config to the firewall
  panos_ipsec_profile:
    provider: '{{ provider }}'
    state: '{{ state }}'
    name: 'ipsec-{{ vpn_connection_id }}'
    esp_authentication: '{{ ike_authentication }}'
    esp_encryption: '{{ ipsec_encryption }}'
    lifetime_seconds: '3600'
    commit: False
    
    
- name: create tunnel.100
  panos_tunnel:
    provider: '{{ provider }}'
    state: '{{ state }}'
    if_name: '{{ tunnel_if_name }}'
    ip: '{{ tunnel_ip }}/30'
    mtu: '{{ tunnel_mtu }}'
    vr_name: '{{ vr_name }}'
    zone_name: '{{ destination_zone_name }}'
    commit: False
    
    
- name: Add IPSec tunnel to IKE gateway profile
  panos_ipsec_tunnel:
    provider: '{{ provider }}'
    state: '{{ state }}'
    name: '{{ tunnel_name}}'
    tunnel_interface: '{{ tunnel_if_name }}'
    ak_ike_gateway: 'ikegw-{{ vpn_connection_id }}'
    ak_ipsec_crypto_profile: 'ipsec-{{ vpn_connection_id }}'
    state: 'present'
    commit: False