################## Start BGP Router IDs #######################
    
- name:  Get Local Cusetomer BGP Router ID
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/customer_gateway/tunnel_outside_address/ip_address
    content: text
  register: local_bgprouter_id_xml
  
- name: Get Local BGP Router ID
  set_fact:
    local_bgprouter_id: "{{ local_bgprouter_id_xml.matches[0].ip_address }}"
  
- name: Debug  Local BGP Router ID
  debug:
    msg: "Local Router ID {{ tunnel_ip }}"
    
################## End BGP Router ID #######################

################## Start BGP Local AS Number #######################
    
- name:  Get BGP Customer AS Number
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/customer_gateway/bgp/asn
    content: text
  register: local_bgp_as_xml
  
- name: Get Local BGP AS Number
  set_fact:
    local_bgp_as: "{{ local_bgp_as_xml.matches[0].asn }}"
  
- name: Debug Local BGP AS Number
  debug:
    msg: "Local BGP AS {{ local_bgp_as }}"
    
################## End BGP Local AS Number #######################

################## Start BGP Remote Peer IP #######################
    
- name:  Get BGP Remote AWS Peer IP
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/vpn_gateway/tunnel_inside_address/ip_address
    content: text
  register: bgp_peer_ip_xml
  
- name: Get BGP Remote Peer IP
  set_fact:
    bgp_peer_ip: "{{ bgp_peer_ip_xml.matches[0].ip_address }}"
  
- name: Debug BGP Remote Peer IP
  debug:
    msg: "Local BGP AS {{ bgp_peer_ip }}"
    
################## End BGP Remote Peer IP #######################

################## Start BGP Remote AS Number #######################
    
- name:  Get BGP Remote AWSD AS Number
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/vpn_gateway/bgp/asn
    content: text
  register: bgp_peer_as_xml
  
- name: Get BGP Remote AS Number
  set_fact:
    bgp_peer_as: "{{ bgp_peer_as_xml.matches[0].asn }}"
  
- name: Debug BGP Remote AS Number
  debug:
    msg: "Local BGP AS {{ bgp_peer_as }}"
    
################## End BGP Remote AS Number #######################

