- name: Gather VPN Facts
  ec2_vpc_vpn_info:
    region: "{{aws_region }}"
  register: awsvpn_facts
  
- name: Debug VPN Facts
  debug:
    msg: "{{ awsvpn_facts }}"
    
- name: Get VPN Connection ID
  set_fact:
    vpn_connection_id: "{{ awsvpn_facts.vpn_connections[0].vpn_connection_id }}"
    
- name: Get VPN GW ID
  set_fact:
    aws_vpn_gw: "{{ awsvpn_facts.vpn_connections[0].vpn_gateway_id }}" 
    
############ Start Build XML File  #######################  
- name: Get XML Variable Output
  set_fact:
    xml_output: "{{ item }}"
  with_together:
    - "{{ awsvpn_facts.vpn_connections|selectattr('state', 'equalto', 'available')|map(attribute='customer_gateway_configuration')|list }}"
    
- name: Save XML Variable to file
  copy:
   content: "{{ xml_output }}"
   dest: "roles/aws_vpn_info/files/aws_output.xml"
   
- name: Replace before the expression till the begin of the file
  replace:
    path: roles/aws_vpn_info/files/aws_output.xml
    before: '<vpn_connection '
    regexp: '^(.+)$'
    replace: ''

- name: Replace all Unsable Characters 1
  replace:
    path: roles/aws_vpn_info/files/aws_output.xml
    regexp: '\\"'
    replace: '"'
    
- name: Replace all Unsable Characters 2
  replace:
    path: roles/aws_vpn_info/files/aws_output.xml
    regexp: '\"\]'
    replace: ''
    
############ End Build XML File  #######################  
    
- name: Get VPN Connection Info from XML file
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/vpn_gateway/tunnel_outside_address/ip_address
    content: text
  register: tunnel_outside_address_xml
  
# - name: Debug Entire XML Variable
#   debug:
#     msg: "{{ tunnel_outside_address_xml }}"
    
#- name: Debug Tunnel Outside IP Address
#  debug: var=tunnel_outside_address_xml.matches[0]['ip_address']

- name: Get Peer AWS ID
  set_fact:
    aws_peer_ip_value: "{{ tunnel_outside_address_xml.matches[0].ip_address }}"   
    
- name: Debug XML AWS Peer ID
  debug:
    msg: "AWS Remote Peer IP {{ aws_peer_ip_value }}"

################## Start Inside Tunnel Address #######################
    
- name:  Get Inside IP Addressing from XML file
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/customer_gateway/tunnel_inside_address/ip_address
    content: text
  register: tunnel_ip_xml
  
- name: Get Local Tunnel IP Address
  set_fact:
    tunnel_ip: "{{ tunnel_ip_xml.matches[0].ip_address }}"
  
- name: Debug Local Tunnel IP Address
  debug:
    msg: "Local Tunnel IP Address {{ tunnel_ip }}"
    
################## End Inside Tunnel Address #######################

################## Start IKE DH Group #######################
    
- name:  Get IKE DH Group
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/ike/perfect_forward_secrecy
    content: text
  register: ike_dh_group_xml
  
- name: IKE Get DH Group
  set_fact:
    ike_dh_group: "{{ ike_dh_group_xml.matches[0].perfect_forward_secrecy }}"
  
- name: Debug Local Tunnel IP Address
  debug:
    msg: "IKE DH Group {{ ike_dh_group }}"
    
################## End IKE DH Group #######################

################## Start IKE Authentication #######################
    
- name:  Get IKE Authentication From XML
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/ike/authentication_protocol
    content: text
  register: ike_authentication_xml
  
- name: IKE Get IKE Authentication
  set_fact:
    ike_authentication: "{{ ike_authentication_xml.matches[0].authentication_protocol }}"
  
- name: Debug IKE Authenication Protocol
  debug:
    msg: "IKE Authentication: {{ ike_authentication }}"
    
################## End IKE IKE Authentication  #######################

################## Start IKE Encryption #######################
    
- name:  Get IKE Encryption From XML
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/ike/encryption_protocol
    content: text
  register: ike_encryption_xml
  
- name: IKE Get IKE Encryption
  set_fact:
    ike_encryption: "{{ ike_encryption_xml.matches[0].encryption_protocol }}"
  
- name: Debug IKE Encryption Protocol
  debug:
    msg: "IKE Encryption: {{ ike_encryption }}"
    
################## End IKE IKE Encryption  #######################


################## Start IKE Lifetime #######################
    
- name:  Get IKE LifeTime From XML
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/ike/lifetime
    content: text
  register: ike_lifetime_xml
  
- name: IKE Get IKE Lifetime
  set_fact:
    ike_lifetime: "{{ ike_lifetime_xml.matches[0].lifetime }}"
  
- name: Debug IKE LifeTtme
  debug:
    msg: "IKE LifeTime: {{ ike_lifetime }}"
    
################## End IKE Lifetime  #######################

################## Start IKE PreShared Key #######################
    
- name:  Get IKE Preshared Key From XML
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/ike/pre_shared_key
    content: text
  register: ike_pre_shared_key_xml
  
- name: Get IKE Preshared Key
  set_fact:
    ike_preshared_key: "{{ ike_pre_shared_key_xml.matches[0].pre_shared_key }}"
  
- name: Debug IKE Preshared Key
  debug:
    msg: "IKE Preshared Key: {{ ike_preshared_key }}"
    
################## End IKE PreShared Key #######################

################## Start IPSec Encryption #######################
    
- name:  Get IPSec Encryption
  xml:
    path: roles/aws_vpn_info/files/aws_output.xml
    xpath: /vpn_connection/ipsec_tunnel/ipsec/encryption_protocol
    content: text
  register: ipsec_encryption_protocol_xml
  
- name: Get IPSec Encryption
  set_fact:
    ipsec_encryption: "{{ ipsec_encryption_protocol_xml.matches[0].encryption_protocol }}"
  
- name: Debug IPSec Encryption
  debug:
    msg: "IPSec Encryption: {{ ipsec_encryption }}"
    
################## End IPSec Encryption #######################

